import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Loader2, Brain, AlertCircle } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

type Segment = {
  text: string;
  ai_probability: number;
  reason?: string;
};

type CheckResult = {
  ai_probability: number;
  human_probability: number;
  confidence?: string;
  reasoning?: string;
  segments?: Segment[];
};

const SAMPLE_TEXTS = {
  ai: "The implementation of artificial intelligence in modern business operations has revolutionized organizational efficiency. Companies are increasingly leveraging machine learning algorithms to optimize their processes. This technological advancement enables enhanced decision-making capabilities and improved operational outcomes.",
  human: "Look, I've been working with AI tools for months now, and honestly? It's pretty wild how much they've changed my workflow. Sure, they're not perfect - sometimes they mess up in hilarious ways - but when they work, they're absolute game-changers for my productivity."
};

const AIChecker = () => {
  const [text, setText] = useState("");
  const [result, setResult] = useState<CheckResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [showHighlights, setShowHighlights] = useState(true);

  const wordCount = text.trim().split(/\s+/).filter(w => w.length > 0).length;

  const handleCheck = async () => {
    if (!text.trim()) {
      toast.error("Please enter some text to check");
      return;
    }

    if (wordCount < 50) {
      toast.error("Please provide at least 50 words for accurate detection");
      return;
    }

    setIsLoading(true);
    setResult(null);

    try {
      const { data, error } = await supabase.functions.invoke('ai-checker', {
        body: { text }
      });

      if (error) {
        toast.error(data?.error || "Failed to analyze text. Please try again.");
        return;
      }

      setResult(data);
      toast.success("Analysis complete!");
    } catch (error) {
      console.error('Error checking text:', error);
      toast.error("Failed to analyze text. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const loadSample = (type: 'ai' | 'human') => {
    setText(SAMPLE_TEXTS[type]);
    setResult(null);
    toast.success(`Sample ${type === 'ai' ? 'AI' : 'human'} text loaded`);
  };

  const getConfidenceColor = (confidence?: string) => {
    if (!confidence) return 'text-muted-foreground';
    switch (confidence.toLowerCase()) {
      case 'high': return 'text-green-500';
      case 'medium': return 'text-yellow-500';
      case 'low': return 'text-orange-500';
      default: return 'text-muted-foreground';
    }
  };

  const getResultZone = (aiProb: number) => {
    if (aiProb >= 70) return { label: 'Likely AI', color: 'from-red-500/20 to-red-600/20 border-red-500/50' };
    if (aiProb >= 40) return { label: 'Uncertain', color: 'from-yellow-500/20 to-yellow-600/20 border-yellow-500/50' };
    return { label: 'Likely Human', color: 'from-green-500/20 to-green-600/20 border-green-500/50' };
  };

  const getSegmentHighlight = (aiProb: number) => {
    if (aiProb >= 70) return 'bg-red-200/80 text-red-900 dark:bg-red-500/30 dark:text-red-100';
    if (aiProb >= 40) return 'bg-yellow-200/80 text-yellow-900 dark:bg-yellow-500/30 dark:text-yellow-100';
    return 'bg-green-200/80 text-green-900 dark:bg-green-500/30 dark:text-green-100';
  };

  const getBreakdownStats = () => {
    if (!result?.segments) return { ai: 0, uncertain: 0, human: 0 };
    
    return result.segments.reduce(
      (acc, segment) => {
        if (segment.ai_probability >= 70) acc.ai++;
        else if (segment.ai_probability >= 40) acc.uncertain++;
        else acc.human++;
        return acc;
      },
      { ai: 0, uncertain: 0, human: 0 }
    );
  };

  const copyAnalysisReport = () => {
    if (!result) return;
    
    const zone = getResultZone(result.ai_probability);
    const stats = getBreakdownStats();
    
    const report = `
AI CONTENT ANALYSIS REPORT
===========================

OVERALL VERDICT: ${zone.label}
AI Probability: ${result.ai_probability}%
Human Probability: ${result.human_probability}%
Confidence Level: ${result.confidence ? result.confidence.charAt(0).toUpperCase() + result.confidence.slice(1) : 'N/A'}

ANALYSIS:
${result.reasoning || 'No detailed reasoning provided'}

BREAKDOWN:
• ${stats.ai} segment(s) flagged as likely AI
• ${stats.uncertain} segment(s) uncertain
• ${stats.human} segment(s) flagged as likely human

Generated by AI Content Detector
    `.trim();
    
    navigator.clipboard.writeText(report);
    toast.success("Analysis report copied to clipboard!");
  };

  const getDetailedSummary = () => {
    if (!result) return '';
    
    const aiProb = result.ai_probability;
    const indicators: string[] = [];
    
    if (result.segments) {
      const stats = getBreakdownStats();
      if (stats.ai > stats.human) indicators.push('repetitive sentence structures');
      if (aiProb >= 70) indicators.push('overly formal tone');
      if (aiProb >= 60) indicators.push('lack of personal voice');
    }
    
    if (aiProb >= 70) {
      return `This text is ${aiProb}% likely to be AI-written. Key indicators: ${indicators.join(', ') || 'multiple AI patterns detected'}.`;
    } else if (aiProb >= 40) {
      return `This text shows mixed characteristics (${aiProb}% AI probability). Some segments may be AI-assisted or edited.`;
    } else {
      return `This text is ${result.human_probability}% likely to be human-written. It shows natural language patterns and personal voice.`;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-primary/5 p-6">
      <div className="max-w-4xl mx-auto space-y-8">
        <div className="text-center space-y-3 animate-in fade-in slide-in-from-top duration-500">
          <div className="inline-flex items-center gap-2 text-primary">
            <Brain className="w-8 h-8" />
          </div>
          <h1 className="text-4xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
            AI Content Detector
          </h1>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Paste your text below and let our advanced AI analyze whether it was written by a human or AI
          </p>
        </div>

        <Card className="p-6 space-y-6 bg-gradient-to-br from-card to-card/80 backdrop-blur border-border/50 shadow-xl animate-in fade-in slide-in-from-bottom duration-700">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium text-foreground">Your Text</label>
              <div className="flex gap-2">
                <Button
                  onClick={() => loadSample('ai')}
                  variant="outline"
                  size="sm"
                  className="text-xs"
                >
                  Try AI Sample
                </Button>
                <Button
                  onClick={() => loadSample('human')}
                  variant="outline"
                  size="sm"
                  className="text-xs"
                >
                  Try Human Sample
                </Button>
              </div>
            </div>
            <Textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Paste your text here for AI detection analysis..."
              className="min-h-[300px] resize-none bg-background/50 border-border/50 focus:border-primary transition-all"
              maxLength={10000}
            />
            <div className="flex justify-between items-center">
              <p className="text-xs text-muted-foreground">
                {text.length} / 10,000 characters • {wordCount} words
              </p>
              {wordCount > 0 && wordCount < 50 && (
                <p className="text-xs text-orange-500 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" />
                  Need 50+ words for accuracy
                </p>
              )}
            </div>
          </div>

          <Button
            onClick={handleCheck}
            disabled={isLoading || !text.trim() || wordCount < 50}
            className="w-full bg-gradient-to-r from-primary to-secondary hover:opacity-90 transition-all shadow-lg hover:shadow-xl"
            size="lg"
          >
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Analyzing...
              </>
            ) : (
              "Check Text"
            )}
          </Button>
        </Card>

        {result && (
          <Card className={`p-8 space-y-6 bg-gradient-to-br ${getResultZone(result.ai_probability).color} backdrop-blur border shadow-xl animate-in fade-in slide-in-from-bottom duration-500`}>
            <div className="flex items-center justify-between">
              <h3 className="text-xl font-semibold">Analysis Results</h3>
              <div className="flex items-center gap-2">
                {result.confidence && (
                  <span className={`text-sm font-medium ${getConfidenceColor(result.confidence)}`}>
                    {result.confidence.charAt(0).toUpperCase() + result.confidence.slice(1)} Confidence
                  </span>
                )}
                <Button
                  onClick={copyAnalysisReport}
                  variant="outline"
                  size="sm"
                  className="text-xs"
                >
                  Copy Report
                </Button>
              </div>
            </div>
            
            <div className="p-4 bg-card/50 rounded-lg border border-border/30">
              <p className="text-center text-2xl font-bold">
                {getResultZone(result.ai_probability).label}
              </p>
              <p className="text-center text-sm text-muted-foreground mt-2">
                {getDetailedSummary()}
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 gap-6">
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-muted-foreground">AI Probability</span>
                  <span className="text-2xl font-bold text-primary">{result.ai_probability}%</span>
                </div>
                <div className="h-3 bg-background rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-primary to-primary/80 transition-all duration-1000 ease-out"
                    style={{ width: `${result.ai_probability}%` }}
                  />
                </div>
              </div>

              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-muted-foreground">Human Probability</span>
                  <span className="text-2xl font-bold text-secondary">{result.human_probability}%</span>
                </div>
                <div className="h-3 bg-background rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-secondary to-secondary/80 transition-all duration-1000 ease-out"
                    style={{ width: `${result.human_probability}%` }}
                  />
                </div>
              </div>
            </div>

            {result.segments && result.segments.length > 0 && (
              <div className="pt-4 border-t border-border/50">
                <div className="flex items-center justify-between mb-3">
                  <h4 className="text-sm font-semibold text-foreground">Breakdown</h4>
                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <div className="w-2 h-2 rounded-full bg-red-500"></div>
                      {getBreakdownStats().ai} AI
                    </span>
                    <span className="flex items-center gap-1">
                      <div className="w-2 h-2 rounded-full bg-yellow-500"></div>
                      {getBreakdownStats().uncertain} Uncertain
                    </span>
                    <span className="flex items-center gap-1">
                      <div className="w-2 h-2 rounded-full bg-green-500"></div>
                      {getBreakdownStats().human} Human
                    </span>
                  </div>
                </div>
              </div>
            )}

            {result.reasoning && (
              <div className="pt-4 border-t border-border/50">
                <p className="text-sm text-muted-foreground">
                  <span className="font-semibold text-foreground">Detailed Analysis: </span>
                  {result.reasoning}
                </p>
              </div>
            )}

            {result.segments && result.segments.length > 0 && (
              <div className="pt-6 border-t border-border/50 space-y-3">
                <div className="flex items-center justify-between">
                  <h4 className="text-sm font-semibold text-foreground">Highlighted Text Analysis</h4>
                  <div className="flex items-center gap-3">
                    <Button
                      onClick={() => setShowHighlights(!showHighlights)}
                      variant="outline"
                      size="sm"
                      className="text-xs"
                    >
                      {showHighlights ? 'Hide' : 'Show'} Highlights
                    </Button>
                    <div className="flex items-center gap-3 text-xs">
                      <div className="flex items-center gap-1">
                        <div className="w-3 h-3 rounded bg-red-200 dark:bg-red-500/30 border border-red-400"></div>
                        <span className="text-muted-foreground">AI</span>
                      </div>
                      <div className="flex items-center gap-1">
                        <div className="w-3 h-3 rounded bg-yellow-200 dark:bg-yellow-500/30 border border-yellow-400"></div>
                        <span className="text-muted-foreground">Uncertain</span>
                      </div>
                      <div className="flex items-center gap-1">
                        <div className="w-3 h-3 rounded bg-green-200 dark:bg-green-500/30 border border-green-400"></div>
                        <span className="text-muted-foreground">Human</span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="p-4 bg-background/50 rounded-lg border border-border/30 leading-relaxed">
                  {result.segments.map((segment, index) => (
                    <span
                      key={index}
                      className={`${showHighlights ? getSegmentHighlight(segment.ai_probability) : ''} px-1 py-0.5 rounded transition-colors cursor-help`}
                      title={segment.reason ? `${segment.reason} (AI: ${segment.ai_probability}%)` : `AI Probability: ${segment.ai_probability}%`}
                    >
                      {segment.text}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </Card>
        )}
      </div>
    </div>
  );
};

export default AIChecker;
